---
title: "Untitled"
output: html_document
date: "2022-10-26"
---

```{r set working directory }
setwd("C:/Users/torriw/Desktop/leah")

```


```{r read in files }
pcs<-read.csv("C:/Users/torriw/Desktop/leah/pcs.csv")
races<-read.csv("C:/Users/torriw/Desktop/leah/allids_with_race.csv")
new_pcs<-read.csv("C:/Users/torriw/Desktop/leah/pcs_graphs.csv")
```


```{r samples}
samples<-c('JWM6682','JWM6209','SMS346','JWM6652','JWM6790','SMS349','JWM6353','JWM6234','JWM6208','SMS329','JWM6579','CCA270','SMS279','JWM6201','JWM6236','CCA258','CCA321','JWM6414','CCA277','SMS348','JWM6301','JWM6354','JWM6495','CCA256','JWM6553','CCA242','JWM6348','JWM6344','JWM6285','JWM6343','JWM6270','JWM6337','CCA317','CCA239','CCA238','SMS295','JWM6249','JWM6286','CCA237','SMS294','CCA236','SMS196','SMS139','SMS195','JWM1044','JWM6719','CCA320','SMS332','CCA319','CCA303','JWM6314','CCA328','JWM6681','CCA310','JWM6686','SMS123','CCA325','SMS328','JWM6691','JWM6621','CCA311','CCA133','SMS119','JWM3324','JWM6257','JWM6513','JWM6503','SMS311','JWM6415','CCA246','SMS317','CCA267','JWM6410','CCA275','CCA255','JWM6431','JWM6400','CCA271','CCA250','SMS314','SMS291','JWM6332','JWM6251','JWM6206','JWM6248','JWM6241','JWM6240','SMS292','CCA209','JWM1054','JWM6670','SMS140','CCA137','CCA138','CCA306','SMS307','JWM6718','CCA312','CCA302','JWM6688','JWM6649','JWM6679','CCA313','CCA332','JWM6665','CCA324','JWM6676','JWM6578','CCA202','CCA323','SMS276','JWM6494','CCA259','CCA268','SMS310','JWM6556','SMS308','JWM6654','JWM6535','JWM6350','JWM6405','SMS325','SMS298','SMS283','CCA145','JWM6266','CCA117','SMS282','SMS121','CCA108','JWM6267','SMS293','SMS110','CCA309','CCA308','SMS252','SMS241','SMS265','SMS240','SMS264','SMS335','SMS327','CCA240','CCA262','SMS334','SMS275','SMS274','SMS290','SMS128','SMS124','JWM6243','SMS168','SMS343','JWM6566','JWM6534','JWM6204','SMS277','CCA168','SMS326','JWM3583','SMS267','JWM6527','SMS300','JWM6380','JWM6242','CCA185','JWM6346','JWM6238','JWM6375','JWM6500','CCA265','JWM3442','CCA333','JWM6255','SMS323','JWM6525','SMS322','JWM6547','CCA106','CCA107','CCA135','CCA147','CCA148','CCA150','CCA161','CCA162','CCA166','CCA167','CCA170','CCA171','CCA173','CCA174','CCA180','SMS157','SMS115','SMS180','SMS136','SMS137','SMS142','SMS154','SMS155','SMS176','SMS184','SMS187','SMS189','SMS199','SMS209','SMS227','SMS228','SMS229','SMS238','CCA111','CCA112','CCA116','CCA149','CCA153','CCA154','CCA157','CCA160','CCA169','CCA182','CCA186','CCA196','SMS101','SMS113','SMS130','SMS133','SMS145','SMS146','SMS148','SMS150','SMS151','SMS156','SMS158','SMS159','SMS161','SMS163','SMS165','SMS170','SMS172','SMS178','SMS179','SMS183','SMS186','SMS193','SMS203','SMS212','SMS224','SMS235','SMS239','SMS244','SMS245','SMS246','SMS247','SMS249','SMS251','SMS255','SMS221','CCA176','CCA175')
 
```

```{r subsetting matching ids from df's}
pc_match<-subset(pcs,globalid %in% samples)
pc_match<-pc_match[1:3] #only pulling first 2 pcs
races_match<-subset(races,globalid %in% samples)
races_match<-races_match[,-3] #remove family column 
combined_df<-cbind(pc_match,races_match[2])
new_pc_match<-subset(new_pcs,globalid %in% samples)
```

```{r plot pc1 vs pc2 }
library(ggplot2)
ggplot(combined_df) +geom_point(aes(x = pc1, y= pc2, color = race)) 
ggplot(new_pc_match) +geom_point(aes(x = pc1, y= pc2, color = race)) 

```
```{r plotting allele effect of snps}
neuro<-read.csv("C:/Users/torriw/Desktop/leah/neuro_file.csv")
genotypes<-read.csv("C:/Users/torriw/Desktop/leah/modified_genotypes.csv")
demgroupclass2<-read.csv("C:/Users/torriw/Desktop/leah/CIFASD_2_demgroupclass.csv")
demgroupclass3<-read.csv("C:/Users/torriw/Desktop/leah/CIFASD_3_demgroupclass.csv")

#match based off id's
demgroupclass2_match<-subset(demgroupclass2,subjectid %in% samples)
demgroupclass3_match<-subset(demgroupclass3,subjectid %in% samples)

# combine df's 
dem_group_combined<-rbind(demgroupclass2_match,demgroupclass3_match)

#remove duplicates from both df's
dups_removed_dem_group<-dem_group_combined[!duplicated(dem_group_combined$subjectid),] 

#write out new df
write.csv(dups_removed_dem_group,"C:/Users/torriw/Desktop/leah/dups_removed_dem_group.csv",row.names = FALSE)


#bar plots rs3199966 
practice<-read.csv("C:/Users/torriw/Desktop/leah/dasiiseqquanreasabil_rs31999.csv")

zscores<- (practice$dasiiseqquanreasabil-mean(practice$dasiiseqquanreasabil))/sd(practice$dasiiseqquanreasabil)
scores<-data.frame(zscores)
practice<-cbind(practice,scores)
# ggplot(practice, aes(x=rs3199966, y=zscores, fill=demgroupclass)) + stat_boxplot(geom = "errorbar")+ geom_boxplot() + scale_y_continuous(
#     expand = c(0, 0),
#     limits = c(min = -1, max =2.0),
#     breaks = seq(-0.8, 2, by = 0.4))
```      

```{r nipun function}
library(dplyr)
#  %>% a pipe that represents "and then"
                  
dataframe_2 <- practice %>%
  group_by(demgroupclass, rs3199966) %>%
  summarise(
    sd = sd(zscores),
    zscores = mean(zscores)
  )
dataframe_2
# write.csv(dataframe_2,"C:/Users/torriw/Desktop/leah/dataframe2.csv",row.names = FALSE)
# write.csv(practice,"C:/Users/torriw/Desktop/leah/zscores.csv",row.names = FALSE)
# png("practice.png", units="in", width=12, height=9, res=600) 
```

```{r}
sets <- c("TT","TG","GG") #name X-axis labels in order you wish
p<- ggplot(data=dataframe_2, aes(x=rs3199966, y=zscores, fill=demgroupclass)) + 
  geom_bar( stat="identity", color="black", size=1.0, #fill=c("#FFFFFF", "#666666"), #this "color" sets the outline color
           position=position_dodge()) +
  geom_errorbar( aes( ymin=zscores-sd, ymax=zscores+sd), width=.2,size=1.0,
               position=position_dodge(0.9)) +
  geom_jitter(data=practice, position = position_dodge(0.9), size=3.0)+
  #geom_point(data=dataframe_Original,aes(x=Organ, y=BAbundance)) +
       #  size = 2, shape = 19, position = position_jitter(width=0.15,  height=0.1)) + #adds individual points
  
 scale_fill_manual(values = c(  "#666666", "#FFFFFF")) + #colors 
  
  scale_y_continuous(limits = c(-2.4,1.8),breaks = seq(-2.4, 1.8, 0.6),expand = c(0,0)) + 
  theme(plot.title = element_text(hjust = 0.5, size=40, face="bold"), 
        axis.title.x = element_blank(), #gets rid of x-axis label
        panel.grid.major = element_blank(), #gets rid of major gridlines
        panel.grid.minor = element_blank(), #gets rid of minor gridlines
        panel.background = element_blank(), #turns background white instead of gray
        axis.line = element_line(colour = "black", size=1.0), axis.ticks = element_line(colour = "black", size = 1.0),
        legend.position="bottom", #gets rid of legend
        legend.title = element_text( size=34, face="bold"), #legend heading
        legend.text = element_text(size=34, 
                                   face="bold"), #legend text
        axis.text=element_text(size=36, color = "black"), #sets size of x and y axis labels
        axis.title=element_text(size=34,face="bold")) + scale_x_discrete (limits = sets) #LABELS X AXIS IN ORDER OF SETS!

p<-p + ggtitle("rs3199966") +ylab("Dasiiseqquanreasabil Mean Zscore")

```

```

